---
pipeline:
  build:
    image: golang:1.11
    commands:
      - go test ./...
      - CGO_ENABLED=0 go build -ldflags "-s" -a -installsuffix cgo -o main.bin
    when:
      event: push
      branch: master

  cr:
    image: plugins/docker
    registry: cr.chuhlomin.com
    repo: cr.chuhlomin.com/busnj-console
    tag:
      - ${DRONE_COMMIT}
      - latest
    username: ${DOCKER_USERNAME}
    secrets: [ docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: skip #master

  deploy:
    image: cr.chuhlomin.com/do-deploy:latest
    username: root
    server: busnj.chuhlomin.com
    docker_image: cr.chuhlomin.com/busnj-console:${DRONE_COMMIT}
    docker_network: beta_default
    docker_network_alias: busnj-console
    container_name: busnj-console
    log_driver: syslog
    envs:
      PORT: "6001"
      PATH_TO_RECEIPTS: /receipts/
    mounts:
      - /var/local/receipts/:/receipts:ro
    expose: "6001"
    secrets:
      - source: ssh_key
        target: ssh_key
    when:
      event: push
      branch: skip #master
