---
pipeline:
  build:
    image: golang:1.13
    commands:
      - make test
      - make vet
      - make build-drone
    when:
      event: push
      branch: master

  cr:
    image: plugins/docker
    context: ./cmd/server
    dockerfile: cmd/server/Dockerfile
    registry: cr.chuhlomin.com
    repo: cr.chuhlomin.com/busnj-console
    tag:
      - ${DRONE_COMMIT}
      - latest
    username: ${DOCKER_USERNAME}
    secrets: [ docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: master

  deploy:
    image: cr.chuhlomin.com/docker-run:latest
    username: root
    server: busnj.chuhlomin.com
    docker_image: cr.chuhlomin.com/busnj-console:${DRONE_COMMIT}
    docker_network: beta_default
    docker_network_alias: busnj-console
    container_name: busnj-console
    log_driver: syslog
    expose: "6001"
    secrets:
      - source: ssh_key
        target: ssh_key
    when:
      event: push
      branch: master
